name: Generate terraform docs
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    terraform_docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.6.0
              with:
                ref: ${{ github.event.pull_request.head.ref }}

            - name: Render terraform docs inside the README.md and push changes back to the PR branch
              uses: terraform-docs/gh-actions@v1.0.0
              with:
                find-dir: .
                output-file: README.md
                output-method: inject
                git-push: 'true'
